export const SHOW_BLOG_POST = "SHOW_BLOG_POST";
export const UNLOAD_BLOG_POST = "UNLOAD_BLOG_POST";

export const SHOW_BLOG_ARCHIVE = "SHOW_BLOG_ARCHIVE";
export const UNLOAD_BLOG_ARCHIVE = "UNLOAD_BLOG_ARCHIVE";

export const LOADING_TOTAL_POST_COUNT = "LOADING_TOTAL_POST_COUNT";
export const SET_TOTAL_POST_COUNT = "SET_TOTAL_POST_COUNT";

export const SHOW_BLOG_ADMIN = "SHOW_BLOG_ADMIN";
export const UNLOAD_BLOG_ADMIN = "UNLOAD_BLOG_ADMIN";
