export const RESET_REQUEST_FLAG = "DATA_AUTHENTICATION_RESET_REQUEST_FLAG";
export const SIGN_OUT = "DATA_AUTHENTICATION_SIGN_OUT";
export const SIGNED_OUT = "DATA_AUTHENTICATION_SIGN_OUT";
export const SIGN_IN_GOOGLE = "DATA_AUTHENTICATION_SIGN_IN_GOOGLE";
export const USER_SIGNED_IN = "DATA_AUTHENTICATION_USER_SIGNED_IN";
